vim.g.mapleader = " "
vim.o.number = true
vim.o.relativenumber = true
vim.o.autocomplete = true
vim.o.completeopt = "menu,fuzzy,menuone,popup"
vim.o.complete = "o"
vim.o.confirm = true
vim.o.termguicolors = true
vim.o.clipboard = "unnamedplus"
