{
  pkgs,
  lib,
  ...
}:
let
  # Define Fish plugins
  fishPlugins = [
    {
      name = "autopair-fish";
      inherit (pkgs.fishPlugins.autopair-fish) src;
    }
    {
      name = "bass";
      inherit (pkgs.fishPlugins.bass) src;
    }
    {
      name = "fzf";
      inherit (pkgs.fishPlugins.fzf) src;
    }
    {
      name = "fish-bd";
      inherit (pkgs.fishPlugins.fish-bd) src;
    }
    {
      name = "hydro";
      inherit (pkgs.fishPlugins.hydro) src;
    }
    {
      name = "nix-env.fish";
      src = pkgs.fetchFromGitHub {
        owner = "lilyball";
        repo = "nix-env.fish";
        rev = "7b65bd228429e852c8fdfa07601159130a818cfa";
        sha256 = "sha256-RG/0rfhgq6aEKNZ0XwIqOaZ6K5S4+/Y5EEMnIdtfPhk=";
      };
    }
  ];

  # Create a file that adds plugin paths to fish_function_path and fish_complete_path
  pluginPaths = lib.concatMapStringsSep "\n" (plugin: ''
    set -gp fish_function_path ${plugin.src}/functions
    set -gp fish_complete_path ${plugin.src}/completions
  '') (lib.filter (p: builtins.pathExists "${p.src}/functions") fishPlugins);

  confDFiles = lib.concatMapStringsSep "\n" (plugin: ''
    if test -d ${plugin.src}/conf.d
      for file in ${plugin.src}/conf.d/*.fish
        source $file
      end
    end
  '') fishPlugins;
in
{
  # Install plugins to ~/.local/share/fish/nix-plugins
  home.file = lib.listToAttrs (
    map (plugin: {
      name = ".local/share/fish/nix-plugins/${plugin.name}";
      value = {
        source = plugin.src;
        recursive = true;
      };
    }) fishPlugins
  );

  # Create init file that sets up plugin paths
  xdg.configFile."fish/conf.d/00-nix-plugins.fish".text = ''
    # Nix-managed Fish plugins
    # This file is automatically generated by Home Manager

    ${pluginPaths}

    # Source conf.d files from plugins
    ${confDFiles}
  '';

  # Add nix-darwin system path (for comma, nix-locate, etc.)
  xdg.configFile."fish/conf.d/01-nix-darwin-path.fish".text = ''
    # Add nix-darwin system packages to PATH
    # This includes comma, nix-locate, and other system-level packages
    if test -d /run/current-system/sw/bin
      fish_add_path /run/current-system/sw/bin
    end
  '';
}
