name: 'Setup Nix'
description: 'Install Nix with flake config accepted'
runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35
      with:
        nix_conf: |
          accept-flake-config = true
